### ISSUE TITLE
Crash when a single diff adds and removes the same element

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#843] opened 2023-03-01 15:01 UTC
I’m doing stress-testing things in my Compose code to create many diffs to the same element. My goal was to exercise view recycling so I created lots of changes to a single element.

My ProtocolBridge soon gets a diff like this:

```
Diff(
  childrenDiffs=[
    Insert(id=Id(value=6), tag=ChildrenTag(value=1), childId=Id(value=12), widgetTag=WidgetTag(value=13), index=0),
    Remove(id=Id(value=6), tag=ChildrenTag(value=1), index=1, count=1), 
    Insert(id=Id(value=6), tag=ChildrenTag(value=3), childId=Id(value=13), widgetTag=WidgetTag(value=13), index=0),
    Remove(id=Id(value=6), tag=ChildrenTag(value=3), index=1, count=1), 
    Insert(id=Id(value=6), tag=ChildrenTag(value=4), childId=Id(value=14), widgetTag=WidgetTag(value=13), index=0),
    Remove(id=Id(value=6), tag=ChildrenTag(value=4), index=1, count=1), 
    Insert(id=Id(value=6), tag=ChildrenTag(value=5), childId=Id(value=15), widgetTag=WidgetTag(value=13), index=0),
    Remove(id=Id(value=6), tag=ChildrenTag(value=5), index=1, count=1)
  ], 
  layoutModifiers=[
    LayoutModifiers(id=Id(value=12), elements=[]), 
    LayoutModifiers(id=Id(value=13), elements=[]), 
    LayoutModifiers(id=Id(value=14), elements=[]), 
    LayoutModifiers(id=Id(value=15), elements=[])
  ],
  propertyDiffs=[
    ...
  ]
)
```

Note that the element with ID 12 is inserted by childrenDiffs[0], and removed with childrenDiffs[3]. This yields a crash applying layout modifiers to a node that’s since vanished:

```
java.lang.IllegalStateException: Unknown widget ID Id(value=12)
	at app.cash.redwood.protocol.widget.ProtocolBridge.node-ou3jOuA(ProtocolBridge.kt:88)
	at app.cash.redwood.protocol.widget.ProtocolBridge.sendDiff(ProtocolBridge.kt:76)
	at app.cash.redwood.treehouse.RealBinding$sendDiff$1.invokeSuspend(bindings.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
```

**Comment by JakeWharton** [comment] 2023-03-01 18:16
This will be resolved by #785

**Comment by JakeWharton** [comment] 2023-04-21 19:20
Do you still have the Composeable that you were using? I mostly want to try and get other things to happen in a single frame like add+move or two moves.

**Comment by JakeWharton** [comment] 2023-04-24 16:32
Closing as duplicate of #785. It's the same problem manifesting in a worse way.

**Closed as not planned by JakeWharton** 2023-04-24 16:32 UTC
Labels: redwood/protocol
