### ISSUE TITLE
Ability to document schema params.

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#832] opened 2023-02-23 21:39 UTC
I'd like to be able to add documentation for the fields in a widget's schema and have those comments be passed through to the widget's generated Compose function. To illustrate:

```kotlin
@Widget(1)
data class Button(
  /** The centered text inside the button. */
  @Property(1) val text: String,
)
```

generates:

```kotlin
/**
 * @field text The centered text inside the button.
 */
@Composable
fun Button(
  text: String,
)
```

I think this would require [UAST](https://plugins.jetbrains.com/docs/intellij/uast.html), but I'm super familiar with it. Maybe there's a better way to accomplish the same goal of documenting widget params?

**Comment by JakeWharton** [comment] 2023-02-23 21:45
This is #19! And it's (nearly) all done on a branch. I had to do all the weird JSON work first because we'll no longer be able to parse the schema or its dependencies anywhere but in the schema module and propagate its info out with only the JSON. I didn't want to land the change before GTFO-ing for two months in case something went wrong. Can you wait until mid-April?

**Comment by colinrtwhite** [comment] 2023-02-23 21:48
No rush on this - I can totally wait! Mostly wanted to start a discussion on the best way to document schemas.

**Comment by JakeWharton** [comment] 2023-02-23 22:25
The docs will also crucially propagate to the widget interface to provide needed context to implementers.

**Comment by JakeWharton** [comment] 2023-04-24 16:53
Duplicate of #19. (Just tidying issue list)

**Closed as not planned by JakeWharton** 2023-04-24 16:53 UTC
