### ISSUE TITLE
[Sample][Emoji] Text input is clipped in Android views

### ISSUE THREAD

**Issue by chrisbanes** [cashapp/redwood#964] opened 2023-04-24 08:43 UTC
This looks to be something a bit deeper into the Redwood view column impl.

| Pixel 6 emulator  | Pixel 3a emulator |
| ------------- | ------------- |
| ![Screenshot_1682325586](https://user-images.githubusercontent.com/227486/233944913-bf53bef2-8df4-43a1-975f-c2aa14455295.png) | ![Screenshot_1682325587](https://user-images.githubusercontent.com/227486/233944918-4110a75d-eb3a-4e14-8034-6ebefc3c558e.png) |

**Comment by chrisbanes** [comment] 2023-04-24 10:55
Looks like this is due to a combination of the underlying RecyclerView being set to `WRAP_CONTENT` height, and then nothing restricting the height. The ideal situation here is to have some sort out `layout_weight` functionality, where the column restricts the height to whatever space is remaining.

**Comment by veyndan** [comment] 2023-04-24 14:49
This looks like a dupe of https://github.com/cashapp/redwood/issues/770. This Issue describes the problem a lot better though!

cc @colinrtwhite

**Closed as completed** 2023-06-09 13:19 UTC
Labels: sample/emoji
